#!/usr/bin/env python3
"""Generate a standalone, version-tolerant single-instance AppImage launcher."""

import argparse
import hashlib
import os
from pathlib import Path
import re
import shlex
import sys
from urllib.parse import unquote, urlsplit


def make_wrapper(appimage):
    filename = appimage.name
    if not filename.lower().endswith('.appimage'):
        raise ValueError('The supplied path must end in .AppImage.')
    stem = filename[:-9]
    # Replace only the first version token; preserve architecture/channel suffixes.
    version = re.search(r'(?<=[_ .-])v?\d+(?:\.\d+)*(?=$|[_ -])', stem)
    if version:
        prefix = stem[:version.start()]
        suffix = filename[version.end():]
        if version.group().startswith('v'):
            prefix += 'v'
        pattern = shlex.quote(str(appimage.parent / prefix)) + '[0-9]*' + shlex.quote(suffix)
        app_name = stem[:version.start()].rstrip('_. -')
    else:
        pattern = shlex.quote(str(appimage))
        app_name = stem
    name = re.sub(r'[^a-z0-9]+', '-', app_name.lower()).strip('-') or 'appimage'
    key = hashlib.sha256(pattern.encode()).hexdigest()[:24]
    script = f'''#!/usr/bin/env bash
# Generated by generate-appimage-wrapper.py. Requires Bash, flock, and GNU sort.
set -euo pipefail
shopt -s nullglob

appimages=({pattern})
files=()
for candidate in "${{appimages[@]}}"; do
    [[ -f "$candidate" ]] && files+=("$candidate")
done
if ((${{#files[@]}} == 0)); then
    echo 'No matching AppImage found; check the configured application directory.' >&2
    exit 1
fi
mapfile -d '' -t files < <(printf '%s\\0' "${{files[@]}}" | LC_ALL=C sort -zV)
appimage=${{files[-1]}}
if [[ ! -x "$appimage" ]]; then
    printf 'AppImage is not executable: %s\\n' "$appimage" >&2
    exit 1
fi

exec flock --no-fork --nonblock --conflict-exit-code 0 \\
    "${{XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR is not set}}/appimage-single-{key}.lock" \\
    "$appimage" "$@"
'''
    return name + '-single', script


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('appimage', help='Local AppImage path, symlink, or file:// URI (not a download URL)')
    parser.add_argument('--output-dir', type=Path, default=Path.home() / '.local/bin',
                        help='Wrapper directory (default: ~/.local/bin)')
    parser.add_argument('--force', action='store_true', help='Replace an existing wrapper')
    args = parser.parse_args()
    try:
        raw = args.appimage
        if raw.startswith('file:'):
            uri = urlsplit(raw)
            if uri.netloc not in ('', 'localhost') or uri.query or uri.fragment:
                raise ValueError('Only local file:// URIs without query or fragment are supported.')
            raw = unquote(uri.path)
        elif '://' in raw:
            raise ValueError('Download the AppImage first, then supply its local path.')
        # Resolve symlinks while still allowing an old version's missing filename.
        appimage = Path(raw).expanduser().resolve()
        if not appimage.parent.is_dir():
            raise ValueError(f'Application directory does not exist: {appimage.parent}')
        name, script = make_wrapper(appimage)
        output_dir = args.output_dir.expanduser().resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
        output = output_dir / name
        # Do not follow an existing symlink, even when --force is requested.
        flags = os.O_WRONLY | os.O_CREAT | os.O_NOFOLLOW
        flags |= os.O_TRUNC if args.force else os.O_EXCL
        fd = os.open(output, flags, 0o755)
        with os.fdopen(fd, 'w') as stream:
            stream.write(script)
            os.fchmod(stream.fileno(), 0o755)
        print(f'Created {output}')
        print('Use this wrapper as the command in your desktop launcher.')
    except (OSError, ValueError) as error:
        print(f'Error: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
